services:

  db:
    env_file:
      - ".env.db"
    image: postgres
    restart: always
    container_name: nestjs_board
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local